### ISSUE TITLE
[Feature] Update `_fivetran_deleted` in `gl_details`

### ISSUE THREAD

**Issue by fivetran-catfritz** [fivetran/dbt_sage_intacct_source#13]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

- I will post the related internal communication in the Height ticket. This history will be very important to understanding this issue!

Source `gl_details` no longer contains column `_fivetran_deleted`. Deletes are now only soft-deleted in the parent table `gl_batch` (see [these release notes](https://fivetran.com/docs/applications/sage-intacct/changelog#january2022)). We will need to:
1. Remove `_fivetran_deleted` from `gl_details` and any downstreams
2. (Optional) Consider bringing in `gl_batch` so users can join to `gl_details` and get the `_fivetran_deleted` column if necessary

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
This has been addressed in the [latest update](https://github.com/fivetran/dbt_sage_intacct_source/releases) to the package. As such, I will close out this feature request.
